name: mental_wellness_tips1
description: A self-help mental wellness Flutter app
publish_to: 'none' # since this is not for publishing

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_auth_web: ^6.1.0
  cloud_firestore: ^6.1.0
  shared_preferences: ^2.2.0
  uuid: ^4.5.2
  fl_chart: ^1.1.1
  material_color_utilities: ^0.11.1
  test_api: ^0.7.7
  characters: ^1.4.0


  # ðŸ‘‰ ADDED: Calendar support
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/breathing.jpg
